-- DropForeignKey
ALTER TABLE "Buy" DROP CONSTRAINT "Buy_userId_fkey";

-- AlterTable
ALTER TABLE "Buy" ALTER COLUMN "userId" DROP NOT NULL,
ALTER COLUMN "date" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "status" SET DEFAULT 'RECEIVED';

-- AddForeignKey
ALTER TABLE "Buy" ADD CONSTRAINT "Buy_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
